networks:
  openldapnet:
    driver: bridge

services:
  ldap:
    image: ${LDAP_IMAGE}
    container_name: openldap
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=false
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    ports:
      - "${LDAP_PORT_LDAP}:389"
    networks:
      - openldapnet

  lam:
    image: ${LAM_IMAGE}
    container_name: lam
    restart: unless-stopped
    environment:
      - LAM_SKIP_PRECONFIGURE=false
      - LAM_PASSWORD=${LAM_PASSWORD}
      - LAM_LANG=en_US
      - LAM_CONFIGURE_CRON=false
      - LAM_CONFIGURATION_DATABASE=files
      - LDAP_SERVER=ldap://ldap:${LDAP_PORT_LDAP}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=cn=admin,${LDAP_BASE_DN}
      - LDAP_USERS_DN=ou=people,${LDAP_BASE_DN}
      - LDAP_GROUPS_DN=ou=groups,${LDAP_BASE_DN}
    ports:
      - "${LAM_PORT_HTTP}:80"
    networks:
      - openldapnet
    depends_on:
      - ldap
