networks:
  openldapnet:
    driver: bridge

services:
  ldap:
    image: ${LDAP_IMAGE}
    container_name: openldap
    restart: unless-stopped
    environment:
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_READONLY_USER=false
    volumes:
      - ./ldap_data:/var/lib/ldap
      - ./ldap_config:/etc/ldap/slapd.d
    ports:
      - "${LDAP_PORT_LDAP}:389"
    networks:
      - openldapnet

  lam:
    image: ${LAM_IMAGE}
    container_name: lam
    restart: unless-stopped
    environment:
      - LAM_SKIP_PRECONFIGURE=true
    volumes:
      - ./lam_config/config:/var/lib/ldap-account-manager/config
      - ./lam_config/config.cfg:/etc/ldap-account-manager/config.cfg
    ports:
      - "${LAM_PORT_HTTP}:80"
    networks:
      - openldapnet
    depends_on:
      - ldap
